- name: clone advanced project temaplate
  shell: composer create-project --prefer-dist --stability=dev yiisoft/yii2-app-advanced /var/www/yii2-app-advanced creates=/var/www/yii2-app-advanced

- name: set Init run permissions
  file: path=/var/www/yii2-app-advanced/init mode=0744

- name: init project
  shell: yes | /var/www/yii2-app-advanced/init --env=Development

- name: set Local config with correct MySQL connection etc. (2 steps to fix Windows shared folder error)
  template: src={{item}} dest=/tmp/{{item}}
  with_items:
   - common-main-local.php
   - frontend-main-local.php
   - backend-main-local.php

- name: set Local config with correct MySQL connection etc. (2 steps to fix Windows shared folder error)
  command: mv /tmp/{{item.src}} {{item.dest}}
  with_items:
   - { src: 'common-main-local.php', dest: '/var/www/yii2-app-advanced/common/config/main-local.php' }
   - { src: 'frontend-main-local.php', dest: '/var/www/yii2-app-advanced/frontend/config/main-local.php' }
   - { src: 'backend-main-local.php', dest: '/var/www/yii2-app-advanced/backend/config/main-local.php' }
